# Setup
title:               Sudha Subramanian
tagline:             'My first blog'
description:         'Made at R-Ladies Meetup'
url:                 https://susub31.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sudha Subramanian
  url:               https://twitter.com/mdo
  email:             su.sub31@gmail.com

# Custom vars
version:             1.0.0
