# Setup
title:               Sudha Subramanian
tagline:             '(Self-motivated & Data-Driven)'
description:         'Click below to learn more ...'
url:                 https://susub31.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sudha Subramanian
  url:               https://twitter.com/sudaspark
  email:             su.sub31@gmail.com

# Custom vars
version:             2.0.0
