# Setup
title:               Sudha SUbramanian
tagline:             'My first blog'
description:         'Made at R-Ladies Meetup'
url:                 https://susub31.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
