# Setup
title:               Sudha Subramanian
tagline:             'Data Driven'
description:         'Passionate about data'
url:                 https://susub31.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sudha Subramanian
  url:               https://twitter.com/sudaspark
  email:             su.sub31@gmail.com

# Custom vars
version:             2.0.0
